In [1]:
import numpy as np

In [2]:
twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])

In [3]:
twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [4]:
twoDArray[1][1]

14

In [5]:
twoDArray[2][2]

12

***Time Complexity : O(1)***

***Space Complexity : O(MN)***

In [11]:
newTwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=1)

In [12]:
twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [13]:
newTwoDArray

array([[ 1, 11, 15, 10,  6],
       [ 2, 10, 14, 11,  5],
       [ 3, 12, 17, 12,  8],
       [ 4, 15, 18, 14,  9]])

In [14]:
newTwoDArray2 = np.insert(twoDArray, 0, [[1,2,3,4]], axis=0)

In [15]:
twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [17]:
newTwoDArray2

array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [18]:
newTwoDArray3 = np.append(twoDArray, [[1,2,3,4]], axis=0)

In [19]:
newTwoDArray3

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 1,  2,  3,  4]])

In [20]:
len(newTwoDArray3) #row length

5

In [21]:
len(newTwoDArray3[0]) #column length

4

In [24]:
def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('Incorrect index')
    else:
        return array[rowIndex][colIndex]

***Time Complexity : O(1)***

***Space Complexity : O(1)***

In [25]:
accessElements(newTwoDArray3, 3, 2)

14

In [26]:
for i in range(5):
    for j in range(4):
        assert accessElements(newTwoDArray3, i, j) == newTwoDArray3[i][j]

In [36]:
def traverseTwoDArray(array):
    for i in range(len(array)): # ------------- O(MN)
        for j in range(len(array[0])): # ------------- O(N)
            print(array[i][j]) # ------------- O(1)

***Time Complexity : O($N^2$)***

***Space Complexity : O(1)***

In [37]:
newTwoDArray3

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 1,  2,  3,  4]])

In [42]:
traverseTwoDArray(newTwoDArray3)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9
1
2
3
4


In [53]:
def searchTwoDArray(array, value):
    for i in range(len(array)): # ------------- O(MN)
        for j in range(len(array[0])): # ------------- O(N)
            if array[i][j] == value: # ------------- O(1)  
                return 'The value is located at index '+str(i)+' , '+str(j) # ------------- O(1)
    return 'The element is not found'

In [54]:
searchTwoDArray(newTwoDArray3, 17)

'The value is located at index 2 , 1'

In [55]:
newTwoDArray3

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 1,  2,  3,  4]])

In [56]:
newTDArray = np.delete(newTwoDArray3, 0, axis=0)
newTDArray

array([[10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 1,  2,  3,  4]])

In [57]:
newTDArray_ = np.delete(newTDArray, 0, axis=1)
newTDArray_

array([[14, 11,  5],
       [17, 12,  8],
       [18, 14,  9],
       [ 2,  3,  4]])

***When to use/avoid Arrays***

***When to use***
- Storing multiple variables of the same data type
- Random access

***When to avoid***
- Storing elements of different data type
- Reserve memory