In [1]:
def productOfArray(arr):
    if len(arr) == 0:
        return 1
    return arr[0] * productOfArray(arr[1:])

In [6]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,5,6])
arr3 = np.array([4,6,7,2])

In [7]:
list_  = [arr1, arr2, arr3]

In [9]:
for i in list_:
    print((i, productOfArray(i)))

(array([1, 2, 3, 4, 5, 6]), 720)
(array([1, 2, 3, 5, 6]), 180)
(array([4, 6, 7, 2]), 336)
